import { Candidate } from '@/types';

export const mockCandidates: Candidate[] = [
  {
    id: '1',
    name: 'John Doe',
    email: 'john@example.com',
    resumeUrl: '#',
    score: null,
    status: 'pre-interview',
    skills: ['React', 'TypeScript', 'Node.js', 'GraphQL'],
    experience: 5,
    education: 'BS Computer Science',
    recruiterId: 'mock-recruiter-id',
  },
  {
    id: '2',
    name: 'Jane Smith',
    email: 'jane@example.com',
    resumeUrl: '#',
    score: null,
    status: 'pre-interview',
    skills: ['Product Management', 'Agile', 'Data Analysis', 'User Research'],
    experience: 7,
    education: 'MBA',
    recruiterId: 'mock-recruiter-id',
  },
  {
    id: '3',
    name: 'Michael Chen',
    email: 'michael@example.com',
    resumeUrl: '#',
    score: null,
    status: 'pre-interview',
    skills: ['Python', 'Machine Learning', 'TensorFlow', 'Data Science'],
    experience: 4,
    education: 'MS Data Science',
    recruiterId: 'mock-recruiter-id',
  },
  {
    id: '4',
    name: 'Sarah Johnson',
    email: 'sarah@example.com',
    resumeUrl: '#',
    score: null,
    status: 'pre-interview',
    skills: ['UI/UX Design', 'Figma', 'User Research', 'Prototyping'],
    experience: 6,
    education: 'BFA Design',
    recruiterId: 'mock-recruiter-id',
  },
  {
    id: '5',
    name: 'David Wilson',
    email: 'david@example.com',
    resumeUrl: '#',
    score: null,
    status: 'pre-interview',
    skills: ['DevOps', 'AWS', 'Kubernetes', 'Docker'],
    experience: 8,
    education: 'BS Software Engineering',
    recruiterId: 'mock-recruiter-id',
  },
];